MedicalUltrasound/Image3dAPI

- Guidelines.md
- README.md
Don't need to expose this information directly on the front page.
> Move implementation gudelines into a separate file

- Image3dAPI/Image3dAPI.vcxproj
- PackagingGE/Image3dAPI.net.targets
- PackagingGE/Image3dAPI.nuspec
Add separate .targets file for .NET projects.
This significantly eases the process of using AppAPI in .NET/C# projects. All that is needed is to add the nuget package to the project, and everything is configured automatically.
> Make NuGet package compatible with .NET

- TestViewer/MainWindow.xaml.cs
Flip Y-Z plane in TestViewer, so that the Y-axis becomes horizontal.
Done to make display consistent with the probe being on the top-center of the image.
> Flip Y-Z plane

- DummyLoader/DummyLoader.vcxproj
- DummyLoader/DummyLoader.vcxproj.filters
- DummyLoader/Image3dSource.cpp
- DummyLoader/Image3dSource.hpp
- DummyLoader/LinAlg.hpp
Extend DummyLoader with resample functionality, so that the output image matches the requested resolution & geometry:
Fixes "broken" output image after https://github.com/MedicalUltrasound/Image3dAPI/pull/61.
> Dummyloader resample support

- TestViewer/MainWindow.xaml.cs
The DrawImages method assumes that the 1st axis is predominantly "X", 2nd is "Y" and 3rd "Z" in the bounding box. This is not necessarily always the case. The CVUS loader e.g. returns "Z" axis as 2nd and "Y" as 3rd. This change makes the TestViewer deal gracefully with this.
> Auto-rearrange 2nd & 3rd axis returned by GetBoundingBox method

- DummyLoader/Image3dSource.cpp
- Image3dAPI/IImage3d.idl
Change the `ProbeType` enum to match IDs from the DICOM standard: http://dicom.nema.org/medical/Dicom/2017b/output/chtml/part16/sect_CID_12035.html
Note that there's no “transthoracic” probe in the enum any more. Not sure if this can become a problem(?). One suggestion from WH is to use "anatomic modifiers": http://dicom.nema.org/medical/Dicom/2017b/output/chtml/part16/chapter_B.html
This **will trigger an API change**, since it changes the binary encoding of the probes.
> API: DICOM-based ProbeType enum

- DummyLoader/GenRgsFiles.py
- Image3dAPI/IImage3d.idl
- Image3dAPI/IImage3dTypeLibraryGenerator.idl
- Image3dAPI/Image3dAPI.vcxproj
- Image3dAPI/Image3dAPI.vcxproj.filters
- Image3dAPI/VersionCheck.hpp
- PackagingGE/Image3dAPI.nuspec
- TestClient/Main.cpp
- TestViewer/MainWindow.xaml.cs
The recent https://github.com/MedicalUltrasound/Image3dAPI/pull/66 introduced an API change which will trigger the need for versioning of Image3dAPI. I'm planning to create a new Image3dAPI 1.1 release, but first want to add some safeguards against accidental mixups of incompatible loader vs. host implementations.
Summary of changes:
* Introduce Image3dAPIVersion enum to expose versioning as part of the API.
* New CheckImage3dAPIVersion function to simplify API version compatibility checking.
* Version the DummyLoader COM class in registry based on the API version in use.
* TestViewer: Check API version for compatibility before opening loader.
* TestClient: Add checking of loader version (disabled due to reg-free COM usage).
> Introduce API version checking

- PackagingGE/PackagePublishNuget.bat
Done to become consistent with doc in https://github.com/MedicalUltrasound/Image3dAPI/blob/master/PackagingGE/BuildNuGet.bat
> Use NuGet.exe from %PATH% instead of hardcoded file-path

- Image3dAPI/IImage3d.idl
Done to simplify, since the UUID values are not really used for anything. UUIDs are only needed for interfaces.
Have already tested on a "clean" Windows installation that the C++, C# and Python scripts still work as before. Therefore, the risk of regressions should be low.
> Remove uuid annotation from enum and struct entries in IDL

- DummyLoader/Image3dSource.cpp
Adjust resolution of underlying checker-board image, so that the checker board squares become perfectly quadratic. Intended to ease investigation of aspect-ratio issues.
Before this PR:
After applying this PR:
Notice that the image slices are not shown in the same scale. That is a separate issues in TestViewer that should be handled separately.
> DummyLoader: Quadratic checker-board squares

- TestViewer/MainWindow.xaml.cs
Done to prevent image and metadata from previous files from still being shown on screen after switching files or loaders. Fixes https://github.com/MedicalUltrasound/Image3dAPI/issues/78.
> TestViewer: Clear UI when opening new files & switching to a new loader

- DummyLoader/Image3dSource.cpp
The existing unsigned integer bounds checking was failing for indices between -0.5 and 0.0, causing mirroring of the image data.
Modifications to MainWindow::DrawImages to make the problem visible:
bbox.origin_x = -0.15f;
bbox.origin_y = -0.1f;
Before this PR:
After applying this PR:
> DummyLoader: Additional bounds checking for negative indices

- TestViewer/MainWindow.xaml.cs
Modify TestViewer, so that all image slices are shown in the same scale on screen. Done by extending the bounding-box, so that all axes gets the same length
Before applying this PR: (notice the Y-Z checker rectangles are larger than the others)
After applying this PR:
> TestViewer: Display image slices in same scale

- DummyLoader/Image3dSource.cpp
- TestClient/Main.cpp
- TestPython/TestPython.py
Running of the C++ & Python test code in "debug" mode is currently quite slow. This PR aims to speed things up a bit by reducing the frame count and image volume sizes.
Changes to ease debugging:
* Reduce DummyLoader frame count from 60 to 25.
* Request smaller image volumes in test code.
* Fix incorrect frame index in python script
There are no API changes in this PR.
> Misc debugging improvements

- DummyLoader/Image3dFileLoader.cpp
- DummyLoader/Image3dFileLoader.hpp
- Image3dAPI/IImage3d.idl
- RegFreeTest/Main.cpp
- SandboxTest/Main.cpp
- TestPython/TestPython.py
- TestViewer/MainWindow.xaml.cs
API change proposal. Intended  to ease client-side error handling. It will in particular enable vendor-specific error messages and enable translation of the messages.
Fixes https://github.com/MedicalUltrasound/Image3dAPI/issues/97.
The enum can be extended with more values on demand.
> API: Add enum for signaling loader failures

- DummyLoader/GenRgsFiles.py
- Image3dAPI/RegistryCheck.hpp
- SandboxTest/Main.cpp
Alternative API proposal to address #90 that stores the manufacturer/model information in the registry.
Done to enable integrators to determine which loader to use **without having to instantiate them**. Based on matching the content of the following DICOM tags:
* (0008,0070) Manufacturer              - exact match
* (0008,1090) Manufacturer's Model Name - exact or '*'/wildcard match
Example registry content:
> API extension to query loaders for supported (manufacturer,model) pairs

- DummyLoader/Image3dSource.cpp
- Image3dAPI/IImage3d.idl
- TestViewer/MainWindow.xaml
- TestViewer/MainWindow.xaml.cs
Proposal to modify the coordinate system to match C.8.X.2.1.2 'Transducer Frame of Reference' in DICOM Enhanced Ultrasound (sup 43). Fixes https://github.com/MedicalUltrasound/Image3dAPI/issues/88.
DummyLoader and TestViewer are updated to deliver the "same" images in the new coordinate system.
Before:
After applying PR:
Note that the Y-Z slice is flipped to Z-Y to maintain orientation. Also, the images shown in the X-Y and X-Z slices are swapped.
> API: Switch to DICOM coordinates

- TestViewer/MainWindow.xaml.cs
Extend implementation to handle empty ECG data. The code already handles E_FAIL (or similar) error-codes.
> Harden TestViewer to deal with two different modes of ECG failure

- TestViewer/MainWindow.xaml.cs
Convert HRESULT error codes into an error message displayed in a pop-up dialog. Intended for debugging of loader issues. Note that this is only helpful for loaders that signal an error. Loaders that crash will still not provide any diagnostics.
> TestViewer: Add diagnostics on GetImageSource failure

- TestViewer/MainWindow.xaml
- TestViewer/MainWindow.xaml.cs
Extend TestViewer app with a button to require creation of a loader in a separate process:
Done to ease testing of process isolation for loaders. Please note that no security controls are implemented in TestViewer, so the loader process will still have the same permissions as the TestViewer parent process.
> Testviewer out-of-process support

- DummyLoader/DummyLoader.idl
- DummyLoader/GenRgsFiles.py
Done to ensure consistency between COM class versions in registry vs. generated type library file (based on the IDL file).
This fixes a current 1.0 vs. 1.2 version inconsistency.
> DummyLoader: Version checking between COM class & API version

- DummyLoader/UNREGISTER_DummyLoader.bat
- Image3dAPI/UNREGISTER_Image3dAPI.bat
Add missing unregistration of type-library. Also, stop specifying "bitness" for entries stored in joint 32/64bit parts of the registry.
> Update unregistration scripts

- RegFreeTest/Main.cpp
- SandboxTest/Main.cpp
Done to ease testing of different loaders from the command-line without having to modify the sources.
> Provide loader ProgID and filename from command-line

- RegFreeTest/Main.cpp
- SandboxTest/Main.cpp
- TestViewer/MainWindow.xaml.cs
Update C++ and C# sample projects to more properly handle `LoadFile` errors.
> Add LoadFile error handling

- SandboxTest/Main.cpp
Image3DLoader should work properly even if input file is read-locked.
> Extend SandboxTest to test scenarios where the file is already read-locked.

- SandboxTest/Main.cpp
Extend compatibility check to also support loaders with non-matching bitness. Done to enable testing of 32bit loaders from a 64bit SandboxTest and vice versa.
> SandboxTest: Enable loaders with non-matching bitness

- TestViewer/MainWindow.xaml.cs
This code will throw if only a loader with non-matching bitness is installed, leading to a crash. This change will at least provide some information back to the user regarding the failure. Also, it's no longer fatal.
The best solution here would be to also search thought the part of the registry with non-matching bitness as SandboxTest already does. However, that can be improved later.
> Add exception catching for version checking code

- SandboxTest/Main.cpp
* Reduce logging unless new "-verbose" command-line argument is provided.
* Enable profiling of the most important API calls through a new "-profile" command-line argument.
Example output when running in "-profile" mode:
```
Open file: C:\Dev\3d_test.dcm to test read-locked input file in loader.
Creating loader GEHC_CARD_US.Image3dFileLoader in low-integrity mode...
CoCreateInstance took 214ms
LoadFile took 69ms
GetImageSource took 19ms
Frame count: 18
GetFrame took 11ms
GetFrame took 9ms
GetFrame took 10ms
GetFrame took 10ms
...
```
Example output when running in "-verbose" mode:
```
Open file: C:\Dev\3d_test.dcm to test read-locked input file in loader.
Creating loader GEHC_CARD_US.Image3dFileLoader in low-integrity mode...
Bounding box:
Origin: -0.0741915, -0.000170385, 0.0742264
Dir1: …
```
> SandboxTest: Add basic loader profiling

- SandboxTest/Main.cpp
To limit log verbosity, only the number of ECG samples is currently logged.
> Extend SandboxTest with Probe and ECG logging

- Image3dAPI/IImage3d.idl
Proposal to clarify API documentation as requested in https://github.com/MedicalUltrasound/Image3dAPI/issues/115.
I don't really have any preference on if lack of ECG should be reported as E_FAIL (or other error code) and/or an empty ECG struct, so we can just as well fail if there's a request for that.
> DOC: Return empty EcgSeries if EGC is not available

- SandboxTest/Main.cpp
Add checking call Image3dSource::GetFrameTimes 
Add printing `Frame times` in verbose mode.
> Extend with printing frame times.

- Image3dAPI/IImage3d.idl
Make it clear that the trig-times are for the R-wave or QRS, depending on terminology. Also, document that the unit is seconds, just like for all other time values.
> Clarify EcgSeries trig_times documentation

- SandboxTest/Main.cpp
Add missing test of GetSopInstanceUID in SandboxTest.
> Add printing SOP Instance UID to test method GetSopInstanceUID.

- SandboxTest/Main.cpp
Add a new command-line option `-threading` to instantiate loader, load file and get image source in a separate thread.
> Move instantiation loader to a separate thread.

- TestViewer/MainWindow.xaml
Done to ease investigation of loader-specific interpolation differences. TestViewer will now display the retrieved image volumes "as is" with no client-side interpolation.
> TestViewer: Disable client-side interpolation

- DummyLoader/DummyLoader.vcxproj
- DummyLoader/DummyLoader.vcxproj.filters
- DummyLoader/Image3dSource.hpp
- DummyLoader/Image3dStream.cpp
- DummyLoader/Image3dStream.hpp
Preparation before upcoming API change. There are no functional changes in this PR.
> Move R8G8B8A8 struct over to a new Image3dStream header

- DummyLoader/DummyLoader.idl
Microsoft states that the COM class version should match the assoicated TypeLib version: https://docs.microsoft.com/en-us/windows/win32/com/version
> DummyLoader: Increase TypeLib version to match COM class versions

- TestPython/TestPython.py
- TestPython/utils.py
Instead, leverage the type libraries already embeded into each vendor's loader DLL. Done to make it easier to use loaders from Python.
> TestPython: Tweak script to no longer depend on a separate TypeLib file

- Image3dAPI/Image3dAPI.vcxproj
> Fix failing post-build registration when there's whitespace in the folder path

- DummyLoader/Image3dSource.cpp
This change clarifies the meaning of the 'duration' of the DummyLoader ECG. The duration of the ECG is the sum of the durations of each individual ECG sample. Each sample is valid from its sample time until the next ECG sample.
This means that in the generated ECG, the last sample has timestamp 'startTime + duration - delta_time', not 'startTime + duration'
> Clarify meaning of ECG 'duration' in DummyLoader sample code

- Image3dAPI/IImage3d.idl
- TestViewer/MainWindow.xaml.cs
The definition of an empty EcgSeries is that all struct members are default constructed, meaning that start_time and delta_time are set to 0.0, and that samples and trig_times are set to null pointers.
This avoids confusion around the meaning of empty EcgSeries, since this could be interpreted as having a zero size samples array. Now it is clear that an empty EcgSeries has a null pointer samples array.
The extension of this definition is that if the samples array is not null, it should at least contain one element. The same applies to the trig_times array.
Replaces #175
> Update GetECG documentation to be explicit on the meaning of empty EcgSeries

- DummyLoader/DummyLoader.vcxproj
- Image3dAPI/Image3dAPI.vcxproj
- RegFreeTest/RegFreeTest.vcxproj
- SandboxTest/SandboxTest.vcxproj
- TestViewer/App.config
- TestViewer/Properties/Resources.Designer.cs
- TestViewer/Properties/Settings.Designer.cs
- TestViewer/TestViewer.csproj
Done to make it easier to build the C++ and C# projects in more recent Visual Studio versions like 2019 and 2022.
> Upgrade projects to VS2019 and .Net 4.8
