MedicalUltrasound/Image3dAPI

- TestViewer/MainWindow.xaml
- TestViewer/MainWindow.xaml.cs
@forderud 
Suggested change: Acquire the three planes for the depiction separately with a modified bounding box instead of plane extraction from one data block.
> Changes in data retrieval

- TestViewer/MainWindow.xaml
@forderud 
Added a pull down menu for selecting various loaders.
> Added a pull down menu

- TestViewer/MainWindow.xaml.cs
@forderud 
With this small change, the slider will be shifted back to initial position if a new file is loaded.
>  The slider jumps back to initial position if a new image is loaded 

- TestPython/TestPython.py
Corrected variable names of vectors defining XYZ-coordinates in image.
Pull request created, as agreed with forderud.
> Corrected variable names of bounding box vectors.

- Image3dAPI/IImage3d.idl
Clarify that the coordinate system axes shall be orthogonal. Also, it follows the right-hand rule.
> Clarify coordinate-system documentation

- DummyLoader/Image3dSource.cpp
This makes the impl. in sync with the documentation.
Before this PR:
After applying this PR:
> DummyLoader: Make plane closest to probe gray

- TestViewer/MainWindow.xaml.cs
Improve scaleBitmap calls to properly deal with oblique directional axes. Also, some other minor changes.
Will be used as basis for a later PR to make image slice resolution better match on-screen resolution.
> Misc TestViewer improvements

- TestPython/TestPython.pyproj
I'm not 100% sure what the changes mean, but Visual Studio seem to want to do these changes automatically when opening the project in VS2017.
> Auto-upgrade the python project

- Image3dAPI/IImage3d.idl
Merging of this PR will be followed by creation of a 1.2 tag.
> Increment API version to 1.2

- SandboxTest/Main.cpp
Based on "Designing Applications to Run at a Low Integrity Level" https://msdn.microsoft.com/en-us/library/bb625960.aspx . This can be verified in "Process Explorer":
This effectively prevents the loader from performing _write_ operations to either disk or registry (except for the temp folder). It does, however, not protect against _read_ operations.
> Harden SandboxTest to launch loader in a "low integrity" process

- TestViewer/MainWindow.xaml
Also, move the GE-internal KretzLoader to the bottom of the list.
> Add CanonLoader to list of known loaders

- Image3dAPI/RegistryCheck.hpp
Extend `CheckImage3dAPIVersion` and `ReadList` functions with optional support for explicitly querying the 32- or 64bit part of the registry.
Done to better support "mixed mode" deployment, where a 64bit loader is accessed out-of-proc from a 32bit host (or vice versa).
> Enable explicit query into 32- or 64-bit part of the registry

- DummyLoader/GenRgsFiles.py
Changes:
* Only make Image3dFileLoader directly creatable, and not Image3dSource. Done, since Image3dSource objects are always retrieved from Image3dFileLoader.
* Only register "SupportedManufacturerModels" and "AppID" for Image3dFileLoader, and not for Image3dSource.
Visual diff of the generated Image3dSource.rgs file before/after this PR:
Image3dFileLoader.rgs remain the same, with just a slight reordering of one entry.
> Simplify DummyLoader COM registration

- TestViewer/MainWindow.xaml
Done to make it easier to test this loader.
> Add HitCV3DLoader.Image3dFileLoader to list of known loaders

- RegFreeTest/Main.cpp
- SandboxTest/Main.cpp
Add console messages to make the error handling more informative.
> Improve SandboxTest & RegFreeTest error handling

- SandboxTest/Main.cpp
Intended to serve as a debugging aid.
> Extend SandboxTest with logging of bounding-box and color-map

- DummyLoader/Image3dSource.cpp
- DummyLoader/Image3dSource.hpp
- RegFreeTest/Main.cpp
- SandboxTest/Main.cpp
Some minor adjustments to the sample code to make the "diff" smaller in a later upgrade of all sample code to the next API version.
There are no functional changes in this PR.
> Update sample code

- RegFreeTest/Main.cpp
- SandboxTest/LowIntegrity.hpp
- SandboxTest/Main.cpp
- SandboxTest/SandboxTest.vcxproj
- SandboxTest/SandboxTest.vcxproj.filters
- TestPython/TestPython.py
Preparation before upcoming API change. There are no functional changes in this PR.
> Adjust sample code

- DummyLoader/Image3dSource.cpp
- DummyLoader/Image3dStream.hpp
will simplify the code later when starting to implement color-flow support.
There are no functional changes in this PR.
> DummyLoader: Introduce CreateImage3d support function

- DummyLoader/Image3dSource.cpp
> DummyLoader: Extend CreateImage3d usage

- TestPython/ITKExport.py
- TestPython/TestPython.py
- TestPython/TestPython.pyproj
- TestPython/utils.py
> TestPython: possibility to save to ITK image

- DummyLoader/Image3dSource.cpp
- DummyLoader/Image3dStream.hpp
- RegFreeTest/Main.cpp
- SandboxTest/Main.cpp
- TestViewer/MainWindow.xaml.cs
Some more cleanup to prepare for the upcoming API upgrade. There are no functional changes in this PR.
> Misc cleanup

- DummyLoader/Image3dSource.cpp
- DummyLoader/Image3dSource.hpp
- DummyLoader/Image3dStream.hpp
- DummyLoader/LinAlg.hpp
DummyLoader generalizations to prepare for multi-byte image data support.
> DummyLoader preparations

- README.md
Based on suggestions in https://github.com/MedicalUltrasound/Image3dAPI/pull/165.
Convert workload list into bullet points and update the wording slightly.
> Update getting started instructions

- DummyLoader/Image3dSource.cpp
- DummyLoader/Image3dSource.hpp
- DummyLoader/LinAlg.hpp
- TestViewer/MainWindow.xaml.cs
Some more cleanup to prepare for the upcoming API upgrade. There are no functional changes in this PR.
> Even more cleanup
